name: Update Data

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch MESISarea_lg.js
      run: |
        curl -o data/MESISarea_lg.js https://weather.121.com.cn/data_cache/szWeather/fenquyubao/MESISarea_lg.js

    - name: Fetch szAlarm.js
      run: |
        curl -o data/szAlarm.js https://weather.121.com.cn/data_cache/szWeather/alarm/szAlarm.js

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git config --global credential.helper store
        echo "https://$(GH_TOKEN)@github.com" > ~/.git-credentials
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Commit and push changes
      run: |
        git add data/MESISarea_lg.js data/szAlarm.js
        git commit -m 'Update MESISarea_lg.js and szAlarm.js'
        git push
